# -------------------------------------------------------------------
# Корневой compose-файл для локального поднятия портала SEAF.Archtool
# 
# ВАЖНО: ознакомьтесь с примером .docker/compose/example.yaml для пере-
# определения необходимых полей и использования в своем проекте
# -------------------------------------------------------------------
services:
  seaf-archtool-core:
    extends:
      file: .docker/compose/.template.yaml
      service: seaf-archtool-core
