@startuml
title "Развитие архитектуры экосистем"
participant "Компания A" as company_a
participant "SEAF.ArchTool A" as archtool_a
participant "Компания B" as company_b
participant "SEAF.ArchTool B" as archtool_b
database "Branch\nCompany A" as rb_company_a
database "Branch\nCompany B" as rb_company_b
database "Branch\nmaster" as rb_master

group Обзор архитектуры
    archtool_a <- rb_company_a : Манифесты
    archtool_a <- rb_master : Манифесты
    company_a <- archtool_a : Артефакты

    archtool_b <- rb_company_b : Манифесты
    archtool_b <- rb_master : Манифесты
    company_b <- archtool_b : Артефакты
end

group Развитие архитектуры
    rb_company_a <- rb_master : Checkout
    company_a <-> rb_company_a : Развитие
    rb_company_a -> rb_master : Pull request
    rb_master -> rb_master : Merge
    rb_company_a <- rb_master : Fetch
end

@enduml
