@startmindmap
* [[https://gitverse.ru/seafteam/seaf-archtool-core SEAF.ArchTool]]
** Управление
*** Управление архитектурой
**** [[/docs/archtool.components Манифесты компонентов]]
***** Инкрементальное развитие
****** [[https://about.gitlab.com/ GitLab]]
**** [[/docs/archtool.contexts Манифесты контекстов]]
***** Инкрементальное развитие
****** [[https://about.gitlab.com/ GitLab]]
**** [[/docs/archtool.aspects Манифесты аспектов]]
***** Инкрементальное развитие
****** [[https://about.gitlab.com/ GitLab]]
*** Управление технологиями
**** [[/docs/archtool.technologies Манифесты технологий]]
***** Инкрементальное развитие
****** [[https://about.gitlab.com/ GitLab]]
*** Управление артефактами
**** [[/docs/archtool.docs Манифесты артефактов]]
***** Инкрементальное развитие
****** [[https://about.gitlab.com/ GitLab]]
** Интеграция
*** Внешние манифесты
**** HTTP
*** Внешние данные
**** [[/docs/archtool.tables Источники данных]]
** Публикация
*** Автоматическая генерация\nартефактов
**** [[/docs/archtool.datasets Источники данных]]
***** [[/docs/archtool.tables Аналитические таблицы]]
***** [[/docs/archtool.templates Шаблоны]]
**** [[/docs/archtool.contexts Диаграммы контекстов]]
***** [[https://plantuml.com/ PlantUML]]
**** [[/docs/archtool.aspects Диаграммы аспектов]]
***** [[https://plantuml.com/ PlantUML]]
*** [[/docs/archtool.docs Пользовательские артефакты]]
**** [[/docs/archtool.docs#plantuml Диаграммы, схемы и т.д.]]
***** [[/docs/archtool.plantuml PlantUML]]
****** [[/docs/archtool.templates Шаблоны]]
***** [[/docs/archtool.mermaid Mermaid]]
****** [[/docs/archtool.templates Шаблоны]]
**** [[/docs/archtool.docs#markdown Документы]]
***** [[https://ru.wikipedia.org/wiki/Markdown Markdown]]
****** [[/docs/archtool.docs#markdown Встраивание объектов SEAF.ArchTool]]
****** [[/docs/archtool.templates#markdown Шаблоны]]
**** [[/docs/archtool.tables Таблицы]]
**** [[/docs/archtool.network Сети]]
**** [[/docs/archtool.docs#swagger Контракты]]
***** [[https://swagger.io/ Swagger]]
****** [[/docs/archtool.templates#openapi Шаблоны]]
***** [[https://www.asyncapi.com/ AsyncAPI]]
****** [[/docs/archtool.templates#asyncapi Шаблоны]]
** Расширяемая метамодель
*** [[/docs/archtool.entities Кастомные сущности]]
@endmindmap
