@startuml
title Диаграмма взаимодействия SEAF.ArchTool
actor "[[/architect/components/archtool.user Пользователь]]" as user
participant "[[/architect/components/archtool.front SEAF.ArchTool]]" as SEAF.ArchTool
participant "[[/architect/components/archtool.gitlab.api GitLab]]" as GitLab
group Авторизация
    user -> SEAF.ArchTool: Вход
    SEAF.ArchTool -> SEAF.ArchTool: Авторизован?
    SEAF.ArchTool -> GitLab: Redirect OAuth
    GitLab -> GitLab: Авторизация
    GitLab -> SEAF.ArchTool: Токен авторизации
end
group Загрузка манифестов
    SEAF.ArchTool -> GitLab: Запрос корневого манифеста
    database "[[/architect/components/archtool.gitlab.repository Репозиторий]]" as repo
    GitLab <- repo: Корневой манифест
    GitLab -> SEAF.ArchTool: Корневой манифест
    SEAF.ArchTool -> SEAF.ArchTool: Обработка манифеста
    group GitLab
        SEAF.ArchTool -> GitLab: Запрос подключаемых\nманифестов через API
        GitLab <- repo: Подключаемый манифест
        SEAF.ArchTool <- GitLab: Подключаемый манифест
    end
    group HTTP
        collections "WEB ресурсы" as web
        SEAF.ArchTool -> web: Запрос подключаемых\nманифестов по HTTP
        web -> SEAF.ArchTool: Подключаемый манифест
    end
    SEAF.ArchTool -> SEAF.ArchTool: Консолидация манифестов
    SEAF.ArchTool -> SEAF.ArchTool: Построение навигационного дерева
end
group Использование
    SEAF.ArchTool -> user: Рабочий стол с\nдеревом навигации
    user -> SEAF.ArchTool: Выбор пункта меню\nиз дерева
    SEAF.ArchTool -> SEAF.ArchTool: Анализ ссылки
    group GitLab
        SEAF.ArchTool -> GitLab: Запрос объекта через API
        GitLab <- repo: Объект
        GitLab -> SEAF.ArchTool: Объект
    end
    group HTTP
        SEAF.ArchTool -> web: Запрос объекта по HTTP
        web -> SEAF.ArchTool: Объект
    end
    SEAF.ArchTool -> SEAF.ArchTool: Рендер объекта
    SEAF.ArchTool -> user: Карточка объекта
end
@enduml
