#!/bin/sh

MSG_HEADER_REGEX="^(ERA-\d{1,}):([\s\w]{2,50})$"

MSG="$1"

header=$(head -1 $MSG)
if ! echo "$header" | grep -Po "$MSG_HEADER_REGEX";
then
    echo "Aborting according commit message policy. Please specify header by rule $MSG_HEADER_REGEX"
    echo "Example: ERA-415: add hooks for check commit message"
    exit 1
fi
